import { ClothItem, PaintItem, CustomerProfile, VendorProfile, SaleEntry, ExpenseEntry } from '../types';

export const initialCustomers: CustomerProfile[] = [
  {
    id: 'cust-1',
    name: 'Anjali Sharma',
    phone: '98250 12345',
    city: 'Ahmedabad',
    address: 'B-402, Satellite Enclave',
    notes: 'Regular customer. Loves gold zari work on silk sarees.',
    createdAt: '2026-06-15',
  },
  {
    id: 'cust-2',
    name: 'Meena Aunty (Neighbor)',
    phone: '98980 67890',
    city: 'Local Society',
    address: 'House No. 14, Sunrise Park',
    notes: 'Brings her own sarees for floral hand painting.',
    createdAt: '2026-06-18',
  },
  {
    id: 'cust-3',
    name: 'Sunita Verma',
    phone: '94265 88123',
    city: 'Patan',
    address: 'Station Road Near Temple',
    notes: 'Prefers co-ord sets and dupattas.',
    createdAt: '2026-07-02',
  },
  {
    id: 'cust-4',
    name: 'Ritu Patel',
    phone: '97129 44556',
    city: 'Gandhinagar',
    address: 'Sector 22',
    notes: 'Friend of Anjali Sharma. Prefers pastel organza sarees.',
    createdAt: '2026-07-10',
  }
];

export const initialVendors: VendorProfile[] = [
  {
    id: 'vend-1',
    shopName: 'Surat Saree Wholesalers',
    category: 'Cloth Wholesaler',
    contactPerson: 'Ramesh Bhai',
    phone: '98240 99887',
    city: 'Surat',
    notes: 'Provides bulk discounts on raw silk and organza sarees.',
    createdAt: '2026-06-01',
  },
  {
    id: 'vend-2',
    shopName: 'Shreeji Stationers & Craft House',
    category: 'Paint Shop',
    contactPerson: 'Paresh Patel',
    phone: '99099 11223',
    city: 'City Market',
    notes: 'Fevicryl and Camel paint dealer. Gives 10% discount on bottles.',
    createdAt: '2026-06-05',
  },
  {
    id: 'vend-3',
    shopName: 'Meesho / Online',
    category: 'Cloth Wholesaler',
    contactPerson: 'Online Platform',
    phone: '1800-ONLINE',
    city: 'Online Delivery',
    notes: 'Good for budget cotton and georgette suit materials.',
    createdAt: '2026-06-10',
  }
];

export const initialCloths: ClothItem[] = [
  {
    id: 'cloth-1',
    clothType: 'Saree',
    fabricCategory: 'Silk',
    purchaseCost: 2800,
    purchaseDate: '2026-07-01',
    purchaseLocation: 'Surat Market',
    vendorId: 'vend-1',
    vendorName: 'Surat Saree Wholesalers',
    quantity: 1,
    status: 'Sold',
    notes: 'Pure raw silk saree with broad plain border, ideal for peacock painting.',
    createdAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'cloth-2',
    clothType: 'Saree',
    fabricCategory: 'Organza',
    purchaseCost: 1200,
    purchaseDate: '2026-07-05',
    purchaseLocation: 'Meesho / Online',
    vendorId: 'vend-3',
    vendorName: 'Meesho / Online',
    quantity: 1,
    status: 'In Stock',
    notes: 'Pastel mint green organza saree for lotus design.',
    createdAt: '2026-07-05T11:30:00Z',
  },
  {
    id: 'cloth-3',
    clothType: 'Dupatta / Stole',
    fabricCategory: 'Silk',
    purchaseCost: 450,
    purchaseDate: '2026-07-10',
    purchaseLocation: 'Local Market',
    vendorId: 'vend-1',
    vendorName: 'Surat Saree Wholesalers',
    quantity: 1,
    status: 'Sold',
    notes: 'Tussar silk white dupatta for marigold painting.',
    createdAt: '2026-07-10T09:15:00Z',
  },
  {
    id: 'cloth-4',
    clothType: 'Salwar Suit',
    fabricCategory: 'Fabric / Cotton',
    purchaseCost: 850,
    purchaseDate: '2026-07-12',
    purchaseLocation: 'Patan Wholesale',
    quantity: 1,
    status: 'In Stock',
    notes: 'Unstitched cotton suit material with plain dupatta.',
    createdAt: '2026-07-12T14:20:00Z',
  },
  {
    id: 'cloth-5',
    clothType: 'Saree',
    fabricCategory: 'Georgette',
    purchaseCost: 1500,
    purchaseDate: '2026-07-15',
    purchaseLocation: 'City Center',
    quantity: 1,
    status: 'In Stock',
    notes: 'Royal blue georgette saree, lightweight for silver zari painting.',
    createdAt: '2026-07-15T16:00:00Z',
  }
];

export const initialPaints: PaintItem[] = [
  {
    id: 'paint-1',
    brandName: 'Fevicryl Silk Color Kit (6 Shades)',
    category: 'Silk Paint',
    description: 'High-fluidity vibrant silk paints designed for raw and Mulberry silk sarees.',
    purchaseCost: 650,
    purchaseDate: '2026-06-25',
    vendorId: 'vend-2',
    vendorName: 'Shreeji Stationers & Craft House',
    isFullyUtilized: false,
    timesUsedCount: 2,
    linkedSaleIds: ['sale-1', 'sale-2'],
    createdAt: '2026-06-25T11:00:00Z',
  },
  {
    id: 'paint-2',
    brandName: 'Camel Acrylic Fabric Colors Set (10 Colors)',
    category: 'Fabric Paint',
    description: 'Standard fast-drying fabric paints for cotton, georgette, and frocks.',
    purchaseCost: 420,
    purchaseDate: '2026-06-28',
    vendorId: 'vend-2',
    vendorName: 'Shreeji Stationers & Craft House',
    isFullyUtilized: false,
    timesUsedCount: 1,
    linkedSaleIds: ['sale-3'],
    createdAt: '2026-06-28T12:00:00Z',
  },
  {
    id: 'paint-3',
    brandName: '3D Metallic Gold Outliner Zari Tubes (3 Pack)',
    category: 'Outliner / Zari',
    description: 'Relief outliner tubes used for gold highlights and border lining.',
    purchaseCost: 280,
    purchaseDate: '2026-07-02',
    vendorId: 'vend-2',
    vendorName: 'Shreeji Stationers & Craft House',
    isFullyUtilized: true,
    fullyUtilizedDate: '2026-07-18',
    timesUsedCount: 2,
    linkedSaleIds: ['sale-1', 'sale-3'],
    createdAt: '2026-07-02T15:30:00Z',
  },
  {
    id: 'paint-4',
    brandName: 'Fine Synthetic Hair Brushes & Fabric Medium',
    category: 'Brushes & Tools',
    description: 'Round brushes (#0, #2, #6) and fabric binder bottle.',
    purchaseCost: 350,
    purchaseDate: '2026-07-04',
    vendorId: 'vend-2',
    vendorName: 'Shreeji Stationers & Craft House',
    isFullyUtilized: false,
    timesUsedCount: 3,
    linkedSaleIds: ['sale-1', 'sale-2', 'sale-3'],
    createdAt: '2026-07-04T10:00:00Z',
  }
];

export const initialSales: SaleEntry[] = [
  {
    id: 'sale-1',
    date: '2026-07-08',
    isCustomerCloth: false,
    linkedClothId: 'cloth-1',
    clothTypeSnapshot: 'Saree (Silk)',
    fabricCategorySnapshot: 'Silk',
    customerId: 'cust-1',
    customerName: 'Anjali Sharma',
    location: 'Ahmedabad',
    sellingPrice: 5500,
    clothPurchaseCost: 2800,
    paintIdsUsed: ['paint-1', 'paint-3', 'paint-4'],
    paintNamesSnapshot: [
      'Fevicryl Silk Color Kit (6 Shades)',
      '3D Metallic Gold Outliner Zari Tubes (3 Pack)',
      'Fine Synthetic Hair Brushes & Fabric Medium'
    ],
    paintCostAllocated: 280, // Calculated pro-rated paint expense contribution
    paymentStatus: 'Paid',
    amountReceived: 5500,
    paymentMode: 'UPI',
    notes: 'Heavy peacock motif hand-painted on silk saree pallu.',
    createdAt: '2026-07-08T14:00:00Z',
  },
  {
    id: 'sale-2',
    date: '2026-07-12',
    isCustomerCloth: true,
    linkedClothId: undefined,
    clothTypeSnapshot: "Customer's Saree (Silk)",
    fabricCategorySnapshot: 'Silk',
    customerId: 'cust-2',
    customerName: 'Meena Aunty (Neighbor)',
    location: 'Local Society',
    sellingPrice: 2200,
    clothPurchaseCost: 0,
    paintIdsUsed: ['paint-1', 'paint-4'],
    paintNamesSnapshot: [
      'Fevicryl Silk Color Kit (6 Shades)',
      'Fine Synthetic Hair Brushes & Fabric Medium'
    ],
    paintCostAllocated: 150,
    paymentStatus: 'Paid',
    amountReceived: 2200,
    paymentMode: 'Cash',
    notes: 'Customer provided her own maroon silk saree. Painted delicate gold-pink floral border.',
    createdAt: '2026-07-12T16:30:00Z',
  },
  {
    id: 'sale-3',
    date: '2026-07-18',
    isCustomerCloth: false,
    linkedClothId: 'cloth-3',
    clothTypeSnapshot: 'Dupatta / Stole (Silk)',
    fabricCategorySnapshot: 'Silk',
    customerId: 'cust-3',
    customerName: 'Sunita Verma',
    location: 'Patan',
    sellingPrice: 1400,
    clothPurchaseCost: 450,
    paintIdsUsed: ['paint-2', 'paint-3', 'paint-4'],
    paintNamesSnapshot: [
      'Camel Acrylic Fabric Colors Set (10 Colors)',
      '3D Metallic Gold Outliner Zari Tubes (3 Pack)',
      'Fine Synthetic Hair Brushes & Fabric Medium'
    ],
    paintCostAllocated: 190,
    paymentStatus: 'Partial',
    amountReceived: 1000,
    paymentMode: 'UPI',
    notes: 'Marigold flower design on white tussar silk dupatta. Pending ₹400 balance.',
    createdAt: '2026-07-18T11:20:00Z',
  }
];

export const initialExpenses: ExpenseEntry[] = [
  {
    id: 'exp-1',
    date: '2026-07-01',
    category: 'Travel',
    amount: 450,
    description: 'Bus fare to & from Surat Market to buy raw silk sarees',
    createdAt: '2026-07-01T18:00:00Z',
  },
  {
    id: 'exp-2',
    date: '2026-07-18',
    category: 'Courier / Shipping',
    amount: 120,
    description: 'Courier parcel to Sunita Verma in Patan for painted dupatta',
    createdAt: '2026-07-18T17:00:00Z',
  },
  {
    id: 'exp-3',
    date: '2026-07-19',
    category: 'Packaging',
    amount: 250,
    description: 'Transparent saree covers with golden ribbon tie-ups (50 pieces)',
    createdAt: '2026-07-19T12:00:00Z',
  }
];
